name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-x86:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/dsaub/redsocial-frontend:x86
        docker push ghcr.io/dsaub/redsocial-frontend:x86
  build-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: 'Login to Github Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/dsaub/redsocial-frontend:arm64
        docker push ghcr.io/dsaub/redsocial-frontend:arm64